### ISSUE TITLE
About pre-log files

### ISSUE THREAD

**Issue by thunanguyen** [chenlq123/MAE#1]
Hi, how can I download the pre-log files for inference and testing ?

**Comment by chenlq123** [comment]
You just need to follow the steps of Preparation I listed in the [Readme](https://github.com/chenlq123/MAE#readme).

**Comment by thunanguyen** [comment]
I've already followed steps in Preparation from 1 to 6 but fail on step 7 because of missing pre-log files and I can't find it anywhere

**Comment by chenlq123** [comment]
It's in step 3. You can find it when you click on the download link, and you need to unzip it.

**Comment by thunanguyen** [comment]
AH! sr for my mistake. Thanks you, I've found it
